version: "3.1"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: maxence
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: CM_IMMO
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init_scripts:/docker-entrypoint-initdb.d/

volumes:
  mongodb_data:
