# Utilisation de l'image officielle MySQL depuis le Docker Hub
FROM mysql:latest

# Informations d'identification pour la base de données (à personnaliser)
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=CM_IMMO
ENV MYSQL_USER=maxence
ENV MYSQL_PASSWORD=password

# Copier les scripts SQL d'initialisation dans le conteneur
COPY permissions.sql /docker-entrypoint-initdb.d/
# COPY ddl.sql /docker-entrypoint-initdb.d/
COPY ddl_tp3.sql /docker-entrypoint-initdb.d/
# COPY init_data.sql /docker-entrypoint-initdb.d/
# COPY cif_tp3.sql /docker-entrypoint-initdb.d/
COPY init_data_tp3.sql /docker-entrypoint-initdb.d/

# Exposer le port MySQL
EXPOSE 3306