version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: cm_immo_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: CM_IMMO
      MYSQL_USER: maxence
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./play_dataset.sql:/docker-entrypoint-initdb.d/play_dataset.sql
      - ./init_scripts:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql
      - ../node_script/CSV:/var/lib/mysql-files
    restart: unless-stopped

volumes:
  mysql_data:
